image: ${JAVA_MAIN_IMAGE_NAME}:${JAVA_MAIN_IMAGE_TAG}

# https://gitlab.com/singletonsd/pipelines/java
include:
  - project: 'singletonsd/pipelines/java'
    file: '/src/.gitlab-ci-main.yml'

variables:
  JAVA_MAIN_IMAGE_NAME: "maven"
  JAVA_MAIN_IMAGE_TAG: "3.5.2-jdk-8"
  JAVA_MAIN_EXECUTE_TEST: "true" # To execute test.
  JAVA_MAIN_EXECUTE_DEPLOY: "false" # To deploy to maven.

stages:
  - build
  - test
  - deploy
  - package
